version: '3.8'
services:
  postgres:
    image: postgres:12
    restart: unless-stopped
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: <ADMINPASS>

  postgrest:
    image: postgrest/postgrest:v7
    depends_on:
    - postgres
    restart: unless-stopped
    environment:
      PGRST_DB_URI: postgres://authenticator:<PASSWORD>@postgres:5432/rcos
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: web_anon

  swagger:
    image: swaggerapi/swagger-ui:v3
    depends_on:
      - postgrest
    restart: unless-stopped
    environment:
        URL: /
        BASE_URL: /swagger

  wikijs:
    image: requarks/wiki:2
    depends_on:
      - postgres
    restart: unless-stopped
    environment:
      DB_TYPE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: authenticator
      DB_PASS: <PASSWORD>
      DB_NAME: wiki

  caddy:
    image: caddy:2
    restart: unless-stopped
    volumes:
    - config/Caddyfile:/etc/caddy/Caddyfile
    - caddy_data:/data

volumes:
  db_data:
  caddy_data:
