version: '3'
services:
    postgrest:
        image: postgrest/postgrest:v7.0.1
        restart: unless-stopped
        environment:
            PGRST_DB_SCHEMA: public
            PGRST_DB_ANON_ROLE: web_anon
            PGRST_OPENAPI_SERVER_PROXY_URI: https://api.rcos.io
            PGRST_DB_URI: "${PGRST_DB_URI}"
            PGRST_JWT_SECRET: "${PGRST_JWT_SECRET}"

    wikijs:
        image: requarks/wiki:2
        restart: unless-stopped
        volumes:
        - /home/rcos/config/wiki.yml:/wiki/config.yml
        - /home/rcos/config/db-cert.crt:/wiki/db-cert.crt

    caddy:
        image: caddy:2
        restart: unless-stopped
        volumes:
        - /home/rcos/config/Caddyfile:/etc/caddy/Caddyfile
        - caddy_data:/data
        ports:
        - "80:80"
        - "443:443"

volumes:
    caddy_data:
